# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Run tests and generate report
      run: |
        mkdir -p test-results
        swift test --enable-code-coverage \
          --parallel \
          --xunit-output test-results/results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: test-results/results.xml
        reporter: java-junit
