# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-macos:
    name: Test Main Libraries (macOS)
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4
    - name: Run tests and generate report
      run: |
        mkdir -p test-results
        swift test --enable-code-coverage --xunit-output test-results/results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Main Libraries - Unit Tests Report
        path: test-results/results-swift-testing.xml
        reporter: java-junit

  test-ios:
    name: Test YouTubeLibrary (iOS Simulator)
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v4

    - name: List available simulators
      run: xcrun simctl list devices available | grep iPhone || true

    - name: Build and test YouTubeLibrary
      run: |
        cd YouTubeLibrary
        set -o pipefail
        xcodebuild test \
          -scheme YouTubeLibrary \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.1' \
          -resultBundlePath test-results/YouTubeLibrary.xcresult \
          -enableCodeCoverage YES
      continue-on-error: false

    - name: Convert xcresult to JUnit XML
      if: always()
      run: |
        cd YouTubeLibrary
        mkdir -p test-results
        xcrun xcresulttool get --format json --path test-results/YouTubeLibrary.xcresult > test-results/results.json || true

    - name: Upload YouTubeLibrary test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: youtube-library-test-results
        path: YouTubeLibrary/test-results
